In [1]:
!pip install scikit-learn

In [2]:
from sklearn.pipeline import Pipeline
##feature scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [3]:
step=[("standard_scaler",StandardScaler()),("classifier",LogisticRegression())]

In [4]:
step

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [5]:
pipe=Pipeline(step)

In [6]:
from sklearn import set_config

In [7]:
set_config(display="diagram")

In [8]:
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [11]:
from sklearn.datasets import make_classification
X,y=make_classification(n_samples=1000)

In [12]:
X . shape

(1000, 20)

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,Y_test = train_test_split(X,y, test_size=0.33, random_state=42)

In [14]:
X_train

array([[ 0.16466139,  0.97883863,  1.80247694, ..., -0.56099088,
         0.24573666, -0.9815774 ],
       [-0.30554745,  1.1177519 , -0.36506326, ..., -0.42738024,
         1.47016866, -0.66289925],
       [ 0.32738509,  0.24546342, -0.23064   , ..., -0.01503121,
        -0.06511868, -2.42605642],
       ...,
       [ 0.6899317 , -1.02111785,  1.45355635, ..., -0.71308766,
        -2.18276577,  1.24251753],
       [-1.15078193,  0.36872656,  0.4896731 , ...,  0.16322331,
         0.88890298,  0.94691792],
       [ 0.20614321, -0.50382981,  1.27707915, ..., -0.43694867,
         0.79806566,  1.40822354]], shape=(670, 20))

In [15]:
pipe.fit(X_train,y_train)
Pipeline(steps=[('standard_scaler', StandardScaler()),
('classifier', LogisticRegression())])
y_pred=pipe.predict(X_test)
y_pred

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1,

In [16]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [17]:
steps=[("scaling",StandardScaler()),
("PCA",PCA(n_components=3)),
("SVC",SVC())]
pipe2=Pipeline(steps)
pipe2.fit(X_train,y_train)
Pipeline(steps=[('scaling', StandardScaler()), ('PCA',
PCA(n_components=3)),
('SVC', SVC())])
pipe2.predict(X_test)

array([0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,

In [18]:
from sklearn.impute import SimpleImputer

In [25]:
import numpy as np
numeric_processor=Pipeline(
steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),("scaler",StandardScaler())])
numeric_processor
Pipeline(steps=[('imputation_mean', SimpleImputer()),('scaler', StandardScaler())])


Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [26]:
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
steps=[("imputation_constant",SimpleImputer(fill_value="missing",strategy="constant")),("onehot",OneHotEncoder(handle_unknown="ignore"))])
categorical_processor
Pipeline(steps=[('imputation_consatnt',SimpleImputer(fill_value='missing',strategy='constant')),('onehot', OneHotEncoder(handle_unknown='ignore'))])

Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing', strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [27]:
## combine processing technqiues
from sklearn.compose import ColumnTransformer

preprocessor=ColumnTransformer(
[("categorical",categorical_processor,["gender","City"]),
("numerical",numeric_processor,["age","height"])]
)
preprocessor
ColumnTransformer(transformers=[('categorical',
Pipeline(steps=[('imputation_consatnt',
SimpleImputer(fill_value='missing',
strategy='constant')),('onehot',
OneHotEncoder(handle_unknown='ignore'))]),
['gender', 'City']),
('numerical',
Pipeline(steps=[('imputation_mean',
SimpleImputer()),
('scaler',
StandardScaler())]),
['age', 'height'])])

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [28]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe
Pipeline(steps=[('columntransformer',
ColumnTransformer(transformers=[('categorical',
Pipeline(steps=[('imputation_consatnt',
SimpleImputer(fill_value='missing',
strategy='constant')),
('onehot',
OneHotEncoder(handle_unknown='ignore'))]),
['gender', 'City']),
('numerical',
Pipeline(steps=[('imputation_mean',
SimpleImputer()),
('scaler',
StandardScaler())]),
['age',
'height'])])),
('logisticregression', LogisticRegression())])

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])